---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install packages 
    package:
      name: 
        - htop
        - tmux
        - vim-nox
        - kitty
        - stellarium
        - eza  
        - remmina
        - ansible
        - stow



# Files for Stow Management
#   .bash_aliases
#   .gitconfig
