---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install server packages 
    package:
      name: 
        - htop
        - tmux
        - vim-nox
        - kitty
        - eza  
        - ansible
        - stow
        - tldr
        - 
tasks:
  - name: install desktop packages 
    package:
      name: 
        - stellarium
        - darktable
        - gimp
        - remmina
        - cmatrix
        - freecad

# Files for Stow Management
#   .bash_aliases
#   .gitconfig

#   run update for tldr index 
#   Clone git dotfiles repo
#   stow dotfiles to ~/
