---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install server packages 
    package:
      name: 
        - htop
        - tmux
        - vim-nox
        - kitty
        - eza  
        - ansible
        - stow
        - tldr
        - unrar
 
tasks:
  - name: install desktop packages 
    package:
      name: 
        - stellarium
        - darktable
        - gimp
        - remmina
        - cmatrix
        - freecad

#install fzf
# git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf
#  ~/.fzf/install

# Files for Stow Management
#   .bash_aliases
#   .gitconfig

#   run update for tldr index 
#   Clone git dotfiles repo
#   stow dotfiles to ~/
